import { Inter } from "next/font/google";
import "./globals.css";
import FooterNavigation from "./TelaLogin/TelaHome/TelaPerfil/Componentes/FooterNavigation";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Teste next App",
  description: "Generated by CJRT with next",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}
        {/* <Footer /> */}
        {/* <FooterNavigation /> */}
      </body>

    </html>
  );
}
